name: notes-yard

image-dock:
  component: "@serverless/website"
  region: ${env.REGION}
  inputs:
    code:
      src: ./build
    bucketName: ${env.BUCKET_NAME}
    domain: notes-yard.smilegupta.tech
      